import 'package:flutter/material.dart';
import 'package:flutterapp/xapapp/generatediphone11prox3widget/generated/GeneratedDownload281Widget.dart';
import 'package:flutterapp/xapapp/generatediphone11prox3widget/generated/GeneratedHelloIvebeeninvitedtoapartybutidontknowifthefoodthereis.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 424.0,
                height: 101.0,
                child:
                    GeneratedHelloIvebeeninvitedtoapartybutidontknowifthefoodthereis(),
              ),
              Positioned(
                left: 0.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 539.0,
                child: GeneratedDownload281Widget(),
              )
            ]),
      ),
    ));
  }
}
